server:
  port: 8082

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://mysql:3306/hrms_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Divy@nshu27k
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
